<a href="https://colab.research.google.com/github/kunal29july/BDA-assign-1/blob/main/Numpybasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
height_in=[74,74,72,72,73,69,69,71,76,71]
weight_lbs=[80,215,210,210,188,176,209,200,233,250]

In [17]:
import numpy as np


In [19]:
height_in=np.array(height_in)
weight_lbs=np.array(weight_lbs)
print(type(height_in))

<class 'numpy.ndarray'>


In [20]:
height_in.size #number of element

10

In [26]:
height_meter=height_in *0.025
weight_kg=weight_lbs *0.45

In [27]:
height_meter


array([1.85 , 1.85 , 1.8  , 1.8  , 1.825, 1.725, 1.725, 1.775, 1.9  ,
       1.775])

In [28]:
weight_kg

array([ 36.  ,  96.75,  94.5 ,  94.5 ,  84.6 ,  79.2 ,  94.05,  90.  ,
       104.85, 112.5 ])

#BMI Calculation

In [29]:
bmi=weight_kg/(height_meter**2)
bmi

array([10.51862673, 28.26880935, 29.16666667, 29.16666667, 25.40063802,
       26.61625709, 31.60680529, 28.56576076, 29.04432133, 35.70720095])

In [30]:
bmi<21

array([ True, False, False, False, False, False, False, False, False,
       False])

In [31]:
bmi>21

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [33]:
bmi[-3:] #last 3

array([28.56576076, 29.04432133, 35.70720095])

In [36]:
bmi[bmi>21].size

9

In [45]:
bmi.max()


35.70720095219202

In [44]:
bmi.min()

10.51862673484295

In [43]:
bmi.mean()

27.406175286189473

#Slicing
(Hint: The syntax is [starting value : end value : step value])

In [48]:
array_1 = [1 ,2, 3, 5 ,4, 6, 7, 8 ,5, 3, 2]
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]
